# Generated by Django 4.1.3 on 2022-11-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_delete_curso_delete_entregable_delete_estudiante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='descripcion',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='familiar',
            name='foto',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
