# Generated by Django 4.1.3 on 2022-11-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_familiar_descripcion_familiar_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='foto',
            field=models.TextField(),
        ),
    ]
